LEFT_BRACE = '{'
RIGHT_BRACE = '}'
LEFT_PARENTHESIS = '('
RIGHT_PARENTHESIS = ')'
COLON = ':'
SEMICOLON = ';'
GREATER_THAN = '>'
LESS_THAN = '<'
ASSIGNMENT = '='
EQUAL = '=='
NOT_EQUAL = '!='
GREATER_THAN_OR_EQUAL = '>='
LESS_THAN_OR_EQUAL = '<='
ADD = '+'
SUB = '-'
MULTI = '*'
DIV = '/'
REM = '%'
POW = '**'
LEFT_SHIFT = '<<'
RIGHT_SHIFT = '>>'
COMMA = ','
POINT = '.'
NOT = '!'
AND = '&'
OR = '|'
XOR = '^'
RESULT = '->'


def get_sign4bool():
    return [EQUAL, NOT_EQUAL, GREATER_THAN_OR_EQUAL, LESS_THAN_OR_EQUAL, AND, OR]
